version: '3'

services:

  flask_plot:
    container_name: flask_plot_docker
    restart: always
    build: ./flask_plot

  nginx:
    container_name: flask_plot_docker_nginx
    restart: always
    build: ./nginx
    ports:
      - "8001:80"
    depends_on:
      - flask_plot
